---
title: "Time plots"
output:
  md_document:
    variant: markdown_github
---
# Create a plot with records vs. time by species 

```{r read}
# Set wd 
machine <- 'ajpelu'

di <- paste('/Users/', machine, '/ownCloud/MS/MS_DP_DISPERSANTES/dp_dispersantes', sep='')

# Read data
df <- read.csv(file=paste(di,"/data/dicc_dwc/ocurrences.csv", sep=""), header=TRUE, sep=";")
```

```{r packages}
library('dplyr')
library('ggplot2')
library('scales')
library('zoo')
```

```{r prepareData}
# Create a variable with only scientific name
df$nombre_cientifico <- paste(df$genus, df$specificepithet, sep=" ")

# Create a subset. 
# Number of records by month and year 

df1 <- df %>% 
  select(year, month, day, eventdate, nombre_cientifico, ocurrenceid) %>% 
  mutate(count=1) %>% 
  mutate(fecha = as.Date(as.yearmon(paste(year,month, sep='-'), format='%Y-%m'))) %>%
  group_by(nombre_cientifico, fecha) %>% 
  summarise(numero=length(nombre_cientifico))


# Change order (allphabetically) to improve the plot
df1 <- within(df1, 
              nombre_cientifico_ord <- ordered(nombre_cientifico, levels=rev(sort(unique(nombre_cientifico)))))
```

```{r plot, fig.height=8, fig.width=12}
p <- ggplot(df1, aes(fecha, nombre_cientifico_ord)) + 
  geom_point(aes(size=numero), shape=15, col='blue') + 
  scale_size_continuous('Number\nof\nRecords', breaks=c(25,50,75,100,150))+
  theme_bw() + scale_x_date(labels=date_format("%Y"), breaks = '1 year') +
  xlab('Year') + ylab('')

p 

tiff(filename = paste(di,'/figures/plot_time_records.tiff',sep=""), width = 1400, height = 1200)
plot(p)
dev.off()

jpeg(filename = paste(di,'/figures/plot_time_records.jpg',sep=""), width = 1400, height = 1200)
plot(p)
dev.off()
```


